tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/fonts'

brew 'awscli'
brew 'git'
brew 'git-extras'
brew 'heroku'
brew 'vim'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
brew 'trash'
brew 'node'

cask 'docker'
cask 'google-chrome'
cask 'paw'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'iterm2'
cask 'gpgtools'
cask 'keybase'
cask 'tunnelbear'
cask 'hyper'

# Fonts
cask 'font-source-code-pro'
